# Dart Feature Flag Cleanup Edges (combined)

# First, remove stale feature flags that are always true or false
[[edges]]
from = "remove_stale_feature_flag_always_true"
to = [
  "simplify_feature_flag_ternary_operator",
  "remove_unnecessary_else_block_for_feature_enabled",
]

[[edges]]
from = "remove_stale_feature_flag_always_false"
to = ["simplify_feature_flag_ternary_operator"]

# Apply ternary simplifications after cleaning up feature flags
[[edges]]
from = "simplify_feature_flag_ternary_operator"
to = ["remove_unnecessary_else_block_for_feature_enabled"]

# Remove the else block after simplifying conditions
[[edges]]
from = "remove_unnecessary_else_block_for_feature_enabled"
to = []
