# Dart Feature Flag Cleanup Rules (combined)

# 1. Remove stale feature flag conditions if the flag is always `true`
[[rules]]
name = "remove_stale_feature_flag_always_true"
query = """
(if_statement
  condition: (parenthesized_expression
    (identifier) @flag (#eq? @flag "{{flag_name}}"))
)
"""
replace = """
{% if flag_value == "true" %}
  // Simplified: removed unnecessary `if (true)` block
  @block
{% endif %}
"""

# 2. Remove stale feature flag conditions if the flag is always `false`
[[rules]]
name = "remove_stale_feature_flag_always_false"
query = """
(if_statement
  condition: (parenthesized_expression
    (identifier) @flag (#eq? @flag "{{flag_name}}"))
)
"""
replace = """
{% if flag_value == "false" %}
  // Simplified: removed block for `if (false)`
{% endif %}
"""

# 3. Simplify feature flag ternary operator
[[rules]]
name = "simplify_feature_flag_ternary_operator"
query = """
(assignment_expression
  right: (conditional_expression
    condition: (parenthesized_expression
      (identifier) @flag (#eq? @flag "{{flag_name}}"))
    consequence: (_) @then
    alternative: (_) @else
  )
)
"""
replace = """
{% if flag_value == "true" %}
  // Simplified: replaced ternary with `then` expression
  @then
{% elif flag_value == "false" %}
  @else
{% endif %}
"""

# 4. Remove unnecessary else block for true feature flag
[[rules]]
name = "remove_unnecessary_else_block_for_feature_enabled"
query = """
(if_statement
  condition: (parenthesized_expression
    (identifier) @flag (#eq? @flag "{{flag_name}}"))
  alternative: (block) @else_block
)
"""
replace = """
{% if flag_value == "true" %}
  // Simplified: removed unnecessary else block
  @block
{% endif %}
"""
