[[rules]]
name = "delete_enum_constant"
query = """
    (
    ((enum_constant name : (_) @n) @ec)
    (#eq? @n  "@stale_flag_name")
    )
    """
replace_node = "ec"
replace = ""
holes = ["stale_flag_name"]
#groups = ["delete_enum_entry"]
