# Dart Feature Flag Cleanup Rules (combined)

# 1. Remove stale feature flag conditions if the flag is always `true`
[[rules]]
name = "remove_stale_feature_flag_always_true"
query = """
(if_statement
  condition: (parenthesized_expression
    (identifier) @flag (#eq? @flag "{{flag_name}}"))
)
"""
replace = """
{% if flag_value == "true" %}
  // Simplified: removed unnecessary `if (true)` block
  @block
{% endif %}
"""
holes = ["flag_name", "flag_value"]

# 2. Remove stale feature flag conditions if the flag is always `false`
[[rules]]
name = "remove_stale_feature_flag_always_false"
query = """
(if_statement
  condition: (parenthesized_expression
    (identifier) @flag (#eq? @flag "{{flag_name}}"))
)
"""
replace = """
{% if flag_value == "false" %}
  // Simplified: removed block for `if (false)`
{% endif %}
"""
holes = ["flag_name", "flag_value"]

# 3. Simplify feature flag ternary operator
[[rules]]
name = "simplify_feature_flag_ternary_operator"
query = """
(assignment_expression
  right: (conditional_expression
    condition: (parenthesized_expression
      (identifier) @flag (#eq? @flag "{{flag_name}}"))
    consequence: (_) @then
    alternative: (_) @else
  )
)
"""
replace = """
{% if flag_value == "true" %}
  // Simplified: replaced ternary with `then` expression
  @then
{% elif flag_value == "false" %}
  @else
{% endif %}
"""
holes = ["flag_name", "flag_value"]

# 4. Remove unnecessary else block for true feature flag
[[rules]]
name = "remove_unnecessary_else_block_for_feature_enabled"
query = """
(if_statement
  condition: (parenthesized_expression
    (identifier) @flag (#eq? @flag "{{flag_name}}"))
  alternative: (block) @else_block
)
"""
replace = """
{% if flag_value == "true" %}
  // Simplified: removed unnecessary else block
  @block
{% endif %}
"""
holes = ["flag_name", "flag_value"]

[[rules]]
name = "remove_unused_enum_entry"
# Query to find an enum entry
query = """
(enum_declaration
  body: (enum_body
    (enum_entry) @enum_entry (#eq? @enum_entry "{{flag_name}}")
  )
)
"""
# Replacement logic to remove the enum entry
replace = """
{% if not is_flag_used %}
  // Removed unused enum entry `{{flag_name}}`
{% endif %}
"""

# Conditions for the rule, to check if the enum entry is used elsewhere
holes = ["flag_name", "is_flag_used"]

[[rules]]
# Check if the enum entry is used anywhere else in the code
name = "check_enum_entry_usage"
query = """
(identifier) @flag_usage (#eq? @flag_usage "{{flag_name}}")
"""
# This will mark the flag as used
replace = """
{% set is_flag_used = true %}
"""

[[rules]]
name = "remove_empty_enum_declaration"
# Query to find an enum declaration with an empty body
query = """
(enum_declaration
  body: (enum_body) @empty_body
    (#eq? @empty_body "{}"))
"""
replace = """
// Removed empty enum declaration
"""

