# Dart Scope Configuration

# Class Scope: Matches class declarations
[[scopes]]
name = "class"
pattern = """
(class_definition
  name: (identifier) @class_name)
"""
description = "Matches a Dart class definition by name."

# Method Scope: Matches method declarations (functions within classes)
[[scopes]]
name = "method"
pattern = """
(method_signature
  (function_signature
    name: (identifier) @method_name)
)
"""
description = "Matches a Dart method declaration inside a class."

# Function Scope: Matches standalone function declarations
[[scopes]]
name = "function"
pattern = """
(function_signature
  name: (identifier) @function_name)
"""
description = "Matches standalone Dart function declarations."

# Block Scope: Matches code blocks such as if-statements or function bodies
[[scopes]]
name = "block"
pattern = """
(block)
"""
description = "Matches a block of Dart code (e.g., if/else blocks, function bodies)."

# Enum Scope: Matches enum declarations
[[scopes]]
name = "enum"
pattern = """
(enum_declaration
  name: (identifier) @enum_name)
"""
description = "Matches an enum declaration by name."

# If-statement Scope: Matches if-statements
[[scopes]]
name = "if_statement"
pattern = """
(if_statement
  condition: (parenthesized_expression) @condition
)
"""
description = "Matches an if-statement with its condition."
